apiVersion: v1
kind: Service
metadata:
  name: frontservice
  namespace: microservices-lab-iteam
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 #container port 
      nodePort: 30011
  type: NodePort