apiVersion: v1
kind: Service
metadata:
  name: usersapiservice
  namespace: microservices-lab-iteam
spec:
  selector:
    app: usersapideployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 8083 #container port 
