
apiVersion: v1
kind: Service
metadata:
  name: logsapiservice
  namespace: microservices-lab-iteam
spec:
  selector:
    app: logsapideployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
