apiVersion: v1
kind: Service
metadata:
  name: todosapiservice
  namespace: microservices-lab-iteam
spec:
  selector:
    app: todosapideployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082 #container port 
